---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: production
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort:
    nodePort: 30008
  type: NodePort
  selector:
   role: frontend
