apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: daradesudarshan/centralrepo:node-app-frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "backend:8080" # assuming backend service is on port 8080
        ports:
        - containerPort: 3000
